# Generated by Django 4.2.7 on 2025-10-30 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=100)),
                ('tipo_equipo', models.CharField(choices=[('Proyector', 'Proyector'), ('Computador', 'Computador'), ('Audio', 'Sistema de Audio'), ('Video', 'Sistema de Video'), ('Mobiliario', 'Mobiliario')], max_length=100)),
                ('marca_modelo', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Sala de Reuniones', 'Sala de Reuniones'), ('Auditorio', 'Auditorio'), ('Laboratorio', 'Laboratorio'), ('Oficina', 'Oficina'), ('Aula', 'Aula')], max_length=100)),
                ('edificio', models.CharField(blank=True, max_length=100, null=True)),
                ('piso', models.IntegerField(blank=True, null=True)),
                ('capacidad', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Mantenimiento', 'Mantenimiento'), ('Fuera de Servicio', 'Fuera de Servicio')], default='Disponible', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('proposito', models.TextField()),
                ('num_asistentes', models.IntegerField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=50)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('comentario_admin', models.TextField(blank=True, null=True)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.espacio')),
                ('id_aprobador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('Usuario', 'Usuario'), ('Admin', 'Administrador'), ('Aprobador', 'Aprobador')], default='Usuario', max_length=50)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.area')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('reserva', 'Reserva'), ('mantenimiento', 'Mantenimiento'), ('incidencia', 'Incidencia'), ('sistema', 'Sistema')], max_length=100)),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mantenimiento', models.CharField(choices=[('Preventivo', 'Preventivo'), ('Correctivo', 'Correctivo'), ('Urgente', 'Urgente')], max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('Programado', 'Programado'), ('En Proceso', 'En Proceso'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], max_length=50)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('id_espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.espacio')),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta'), ('Crítica', 'Crítica')], default='Media', max_length=50)),
                ('estado', models.CharField(choices=[('Reportada', 'Reportada'), ('En Proceso', 'En Proceso'), ('Resuelta', 'Resuelta'), ('Cerrada', 'Cerrada')], default='Reportada', max_length=50)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('acciones_tomadas', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.equipamiento')),
                ('id_espacio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.espacio')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias_reportadas', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HorariosDisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20)),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
                ('fecha_inicio_vigencia', models.DateField()),
                ('bloques_disponibles', models.IntegerField(default=1)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.espacio')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('Cancelada', 'Cancelada')], max_length=50)),
                ('fecha_accion', models.DateField(auto_now_add=True)),
                ('hora_accion', models.TimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.reserva')),
                ('usuario_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='id_espacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamientos', to='reservas.espacio'),
        ),
    ]
