# Generated by Django 5.2.7 on 2025-10-30 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AddField(
            model_name='notificacion',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.reserva'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('reserva_aprobada', 'Reserva Aprobada'), ('reserva_rechazada', 'Reserva Rechazada'), ('reserva_cancelada', 'Reserva Cancelada'), ('reserva_pendiente', 'Reserva Pendiente'), ('reserva_creada', 'Reserva Creada'), ('mantenimiento', 'Mantenimiento'), ('incidencia', 'Incidencia'), ('sistema', 'Sistema')], max_length=100),
        ),
    ]
