# Generated by Django 4.2.7 on 2025-10-31 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_notificacion_options_notificacion_reserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='reservas.reserva'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('Usuario', 'Usuario'), ('Docente', 'Docente'), ('Investigacion', 'Investigación'), ('Administrativo', 'Administrativo'), ('Aprobador', 'Aprobador')], default='Usuario', max_length=50),
        ),
    ]
