# Generated by Django 4.2.7 on 2025-10-31 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservas', '0003_alter_notificacion_reserva_alter_perfilusuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('reserva_creada', 'Nueva Reserva Creada'), ('reserva_aprobada', 'Reserva Aprobada'), ('reserva_rechazada', 'Reserva Rechazada'), ('reserva_cancelada', 'Reserva Cancelada'), ('usuario_registrado', 'Nuevo Usuario Registrado'), ('espacio_creado', 'Espacio Creado'), ('espacio_editado', 'Espacio Editado'), ('espacio_eliminado', 'Espacio Eliminado'), ('incidencia_reportada', 'Incidencia Reportada'), ('reporte_generado', 'Reporte Generado'), ('sesion_iniciada', 'Sesión de Admin Iniciada'), ('sesion_cerrada', 'Sesión de Admin Cerrada'), ('sistema', 'Evento del Sistema')], max_length=100)),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=50)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('espacio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_admin_espacio', to='reservas.espacio')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_admin_reserva', to='reservas.reserva')),
                ('usuario_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_admin_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación de Administrador',
                'verbose_name_plural': 'Notificaciones de Administrador',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
