# Generated by Django 5.2.7 on 2025-12-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_notificacionadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Usuario', 'Usuario'), ('Docente', 'Docente'), ('Investigacion', 'Investigación'), ('Administrativo', 'Administrativo'), ('Aprobador', 'Aprobador')], default='Usuario', max_length=50),
        ),
    ]
