# Generated by Django 4.2.7 on 2025-12-23 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_onetimepassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del elemento')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('computacion', 'Computación'), ('electronica', 'Electrónica'), ('mobiliario', 'Mobiliario'), ('redes', 'Redes'), ('otros', 'Otros')], default='otros', max_length=50)),
                ('codigo_patrimonial', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código Patrimonial')),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('serie', models.CharField(blank=True, max_length=100)),
                ('cantidad_total', models.PositiveIntegerField(default=1, verbose_name='Cantidad total')),
                ('cantidad_disponible', models.PositiveIntegerField(default=1, verbose_name='Cantidad disponible')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'Prestado'), ('mantenimiento', 'En Mantenimiento'), ('baja', 'Dado de Baja')], default='disponible', max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=200, verbose_name='Ubicación física')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='elementos/')),
                ('fecha_adquisicion', models.DateField(blank=True, null=True, verbose_name='Fecha de adquisición')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor aproximado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Elemento',
                'verbose_name_plural': 'Elementos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='observaciones_elementos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='requiere_elementos',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ElementoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('prestado', models.BooleanField(default=False)),
                ('devuelto', models.BooleanField(default=False)),
                ('fecha_prestamo', models.DateTimeField(blank=True, null=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('observaciones_prestamo', models.TextField(blank=True, null=True, verbose_name='Observaciones del préstamo')),
                ('observaciones_devolucion', models.TextField(blank=True, null=True, verbose_name='Observaciones de la devolución')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_asociadas', to='reservas.elemento')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos_detalle', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Elemento de Reserva',
                'verbose_name_plural': 'Elementos de Reserva',
                'unique_together': {('reserva', 'elemento')},
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='elementos',
            field=models.ManyToManyField(blank=True, related_name='reservas', through='reservas.ElementoReserva', to='reservas.elemento'),
        ),
    ]
