# Generated by Django 5.2.7 on 2025-12-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_elemento_reserva_fecha_aprobacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='elementos',
            field=models.ManyToManyField(blank=True, related_name='reservas', through='reservas.ElementoReserva', through_fields=('reserva', 'elemento'), to='reservas.elemento'),
        ),
    ]
